default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: admin
  password: password

development:
  <<: *default
  database: development

test: &TEST
  <<: *default
  database: test

production:
  <<: *default
