---

  - name: Install EPEL
    yum: name=epel-release state=latest

  - name: Install ansible
    yum: name=ansible state=latest

  - name: Disable host checking in absible
    lineinfile: dest=/etc/ansible/ansible.cfg regexp="host_key_checking" insertafter="^\[defaults\]" line="host_key_checking = False"
