---

  - name: copy rspec job config xml
    copy: src=run_spec_config.xml dest=/var/lib/jenkins/run_spec.xml

  - name: Install rspec jobs
    shell: cat /var/lib/jenkins/run_spec.xml | java -jar ~/jenkins-cli.jar -s http://localhost:8080/ create-job run_specs

  - name: copy jasmine job config xml
    copy: src=jasmine_config.xml dest=/var/lib/jenkins/jasmine_spec.xml

  - name: Install jamsime jobs
    shell: cat /var/lib/jenkins/jasmine_spec.xml | java -jar ~/jenkins-cli.jar -s http://localhost:8080/ create-job run_jasmine