---

  - name: Get the jenkins-cli jarfile from the Jenkins server.
    get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=~/jenkins-cli.jar
    register: jarfile_get
    until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
    retries: 8
    delay: 5

  - name: Create Jenkins updates folder.
    file: path=/var/lib/jenkins/updates owner=jenkins group=jenkins mode=0755 state=directory

  - name: Update Jenkins plugin data.
    shell:
      curl -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
      creates=/var/lib/jenkins/updates/default.json

  - name: Install Jenkins plugins.
    command: java -jar ~/jenkins-cli.jar -s http://localhost:8080/ install-plugin {{ item }} creates=/var/lib/jenkins/plugins/{{ item }}.jpi
    with_items: jenkins_plugins
    notify: restart jenkins

  - name: copy job config xml
    copy: src=bundle_unit_job_config.xml dest=/var/lib/jenkins/bundle_unit_job_config.xml

  - name: Install jobs
    shell: cat /var/lib/jenkins/bundle_unit_job_config.xml | java -jar ~/jenkins-cli.jar -s http://localhost:8080/ create-job bundle_units
